version: "3.9"

services:
  redis:
    image: redis:7-alpine
    container_name: zipper-redis
    ports:
      - "6379:6379"

  worker:
    build: .
    container_name: zipper-worker
    command: celery -A celery_app.celery_app worker --loglevel=info
    depends_on:
      - redis
    environment:
      - CELERY_BROKER_URL=redis://redis:6379/0
      - CELERY_RESULT_BACKEND=redis://redis:6379/1
    volumes:
      - .:/app
      - ./zips:/app/zips

  cli:
    build: .
    container_name: zipper-cli
    depends_on:
      - redis
    entrypoint: ["python", "cli.py"]
    volumes:
      - .:/app
      - ./zips:/app/zips
