services:
  redis:
    image: redis:7-alpine
    container_name: zipper-redis
    ports:
      - "6379:6379"

  worker:
    build: .
    container_name: zipper-worker
    command: celery -A src.worker.celery_app.celery_app worker --loglevel=info
    depends_on:
      - redis
    environment:
      - CELERY_BROKER_URL=redis://redis:6379/0
      - CELERY_RESULT_BACKEND=redis://redis:6379/1
    volumes:
      - .:/app
      - ./zips:/app/zips

  flower:
    build: .
    container_name: zipper-flower
    command: celery -A src.worker.celery_app.celery_app flower --port=5555
    depends_on:
      - redis
    environment:
      - CELERY_BROKER_URL=redis://redis:6379/0
      - CELERY_RESULT_BACKEND=redis://redis:6379/1
    ports:
      - "5555:5555"


  cli:
    build: .
    container_name: zipper-cli
    depends_on:
      - redis
    entrypoint: ["zipper", ""]
    volumes:
      - .:/app
      - /home/ifedayo/playbook/zip_data/input:/app/to_zip
      - /home/ifedayo/playbook/zip_data/output:/app/zips
