services:
  redis:
    image: redis:7-alpine
    container_name: zipper-redis
    ports:
      - "6379:6379"

  worker:
    image: ghcr.io/pharmlovex/zipper_app:latest
    command: celery -A src.worker.celery_app.celery_app worker --loglevel=info
    depends_on:
      - redis
    environment:
      - CELERY_BROKER_URL=redis://redis:6379/0
      - CELERY_RESULT_BACKEND=redis://redis:6379/1
    volumes:
      - /prism_genomics/input/prism:/app/to_zip
      - /prism_genomics/output:/app/zipped_outputs
  flower:
    image: ghcr.io/pharmlovex/zipper_app:latest
    container_name: zipper-flower
    command: celery -A src.worker.celery_app.celery_app flower --port=5555
    depends_on:
      - redis
    environment:
      - CELERY_BROKER_URL=redis://redis:6379/0
      - CELERY_RESULT_BACKEND=redis://redis:6379/1
    ports:
      - "5555:5555"


  cli:
    image: ghcr.io/pharmlovex/zipper_app:latest
    container_name: zipper-cli
    depends_on:
      - redis
    environment:
      - CELERY_BROKER_URL=redis://redis:6379/0
      - CELERY_RESULT_BACKEND=redis://redis:6379/1
    command: zipper /app/to_zip --output-dir /app/zipped_outputs
    volumes:
      - /prism_genomics/output:/app/zipped_outputs
      - /prism_genomics/input/prism:/app/to_zip